### ISSUE TITLE
The process cannot access DLL files

### ISSUE THREAD

**Issue by ninjelli** [FortuneN/FineCodeCoverage#13]
I am currently unable to run the code coverage from Visual Studio. I currently receive the following error when it tries to run:

```
Fine Code Coverage : Synchronize Output Files To Work Folder (Test) Failed
System.IO.IOException: The process cannot access the file 'C:\Users\me\AppData\Local\FineCodeCoverage\[Hex folder name]\[Project name].dll' because it is being used by another process.
```

I attempted to exclude the first .dll that I got this error on, but this issue is happening with all of my .dll files.

**Comment by FortuneN** [comment]
Something on the machine is locking those files.
- Maybe an unfinished prior executing
- Maybe antivirus software 
e.t.c

One of the reasons for "Synchronize-ing Output Files To Work Folder" files elsewhere was so that no other software would know where it was (including visual studio).

I'm not sure i can help with this one.
I get this issue from time to time with other software and
- sometimes running as admin works
- sometimes you must find out who is locking the folder (it could be you; if you have windows explorer open in that folder)

**Comment by FortuneN** [comment]
If you can, please provide a simple repro that i can test against

**Comment by ninjelli** [comment]
The only process that is using the file is Visual Studio, according to my resource manager. I run Visual Studio on admin mode, unless you are referring to running the code coverage command from a command prompt in admin mode.

**Comment by FortuneN** [comment]
Please try the latest version and let me know how it goes

**Comment by FortuneN** [comment]
Is the issue resolved; Can i close?

**Comment by FortuneN** [comment]
Please post a review 

https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
