### ISSUE TITLE
Processing test results taking long without indication of progress

### ISSUE THREAD

**Issue by jadaml** [FortuneN/FineCodeCoverage#224]
### Installed product versions
- Visual Studio: 2019 Professional
- This extension: 1.1.154

### Description
I have a lot of unit test package, on a big project, that takes a long time for Fine Code Coverage to process. During this process, nothing is shown in the FCC window. It would be nice if there is some sort of visual indication in this window as well, that the tests being processed.

### Steps to recreate
1. Implement a big system with lot of tests, that may or may not runs for a minute at least;
2. Run the tests;
3. Open the FCC window;
4. Wait for the tests to complete;
5. Right after completion, check the FCC window.

### Current behavior
The window remains empty during the period of Open Coverage processing the coverage data. Just checked the output window in FCC, and seen that during this period, the "=== DONE ===" line have not yet been printed. This is a fair amount of time; I would place it between 10~30 minutes (not measured).

I'm actually surprised by this myself, because if I run Open Cover from console, it does not take this long.

### Expected behavior
At least a marque indicator on the FCC window, or—if possible—a status message indicator on the VS status bar, that the Open Cover is still processing the results would be nice.

While my case is an extreme one, I believe a <5 second long progress should also require such indication, as it currently provide no indication, that it is working at all.

### Side Notes
I strongly believe that Open Cover takes such long time because of the size and complexity of the project, maybe even the number of test being processed (currently 260). I cannot share the source code of the project, because of my NDA.

**Comment by jasells** [comment]
I see similar behavior (~10-30 sec to refresh the output window) after running XUnit tests (~500) with coverlet.msbuild package installed on my test project(s).

The time to refresh itself seems long likely a target for an improvement, but at least an indication (other than the previous results are cleared) that work is progressing would be great!

**Comment by tonyhallett** [comment]
@jadaml @jasells 
It appears that you have not noticed a critical aspect of FCC's behavior.

> RunInParallel					   By default tests run and then coverage is performed.  Set to true to run coverage immediately

> Steps to recreate
> Implement a big system with lot of tests, that may or may not runs for a minute at least;
> 
> Run the tests;
> Open the FCC window;
> Wait for the tests to complete;
> Right after completion, check the FCC window.
> 
> Current behavior
> The window remains empty during the period of Open Coverage processing the coverage data.

Unless you have set RunInParallel Open Cover has not yet begun processing.

> Expected behavior
> At least a marque indicator on the FCC window, or—if possible—a status message indicator on the VS status bar, that the Open Cover is still processing the results would be nice.
> 
> While my case is an extreme one, I believe a <5 second long progress should also require such indication, as it currently provide no indication, that it is working at all.

The FCC Window is for coverage results.  It will clear when new coverage begins though.  
The FCC Output window provides details of the FCC process.  It informs you of the following 

1. When it begins ( as controlled by your RunInParallel option )
2. For each test project - that is running the cover tool and the arguments used
3. Processing of the coverage report/s with ReportGenerator to generate the html report ( and a cobertura file used for the editor margin indicators )
4. That we are further processing the output from ReportGenerator
5. Success 
Then we update the editor and the FCC Window

So we always provide an indication that it is working and it only begins working when either the tests have all finished or you set RunInParallel.  Perhaps what is missing then is a log message when RunInParallel is false - "You could speed up coverage by setting RunInParallel to true".

We could provide a marque indicator that we are still processing but I cannot see how that provides any more information than we have started running the coverage tool and have not started the next step.

We could write to the status bar but then we will be overwriting what the test explorer has written.

------------------------
@jasells 

> The time to refresh itself seems long likely a target for an improvement,

There will be an immediate speed up by setting RunInParallel.  In addition to what I have mentioned above FCC will also copy any dlls that have changed but I doubt that affects performance.  There is one place in the code that can be improved although it will only have an effect if you have multiple test dlls.  Currently coverage is sequential for each test project rather than Task.WhenAll.  I will correct that code tomorrow.

> with coverlet.msbuild package installed on my test project(s).
We do not use that.

**Comment by tonyhallett** [comment]
@FortuneN 
Task.WhenAll ?
https://github.com/FortuneN/FineCodeCoverage/blob/57ab67780f011e0b69756f4828acd18fefaa3c41/SharedProject/Core/FCCEngine.cs#L133

**Comment by FortuneN** [comment]
- Task.WhenAll(...)
- AsParallel().ForAll(...)
- 

Whichever seems better

I made decisions on this when I was still trying to get the sequence of events in way that's easy to track with the text-based logs (if a recall correctly)

We certainly can make the processing of coverage projects parallel

The challenge (I think) is to produce a log (progress report) that is readable

Maybe it's time to look into a more appealing graphical progress that can the progress of each project (something like download manager that shows multiple simultaneous processes and the progress of each)

**Comment by jasells** [comment]
> Maybe it's time to look into a more appealing graphical progress indicator that can show the progress of each project (something like download manager that shows multiple simultaneous processes and the progress of each)

Yah, that's something like what I was trying to suggest.  =)

Overall, very useful tool!  If this is all I have to complain about, you're doing pretty well!

**Comment by jasells** [comment]
> > with coverlet.msbuild package installed on my test project(s).
> > We do not use that.

Cool, just supplying as much information as possible.  My pipelines use that, and many of the options for the extension match, so wasn't sure how you were plugging into the local build system.  I guess through VS-test-runner api's?  (Just curious)

**Comment by jasells** [comment]
> The FCC Window is for coverage results. It will clear when new coverage begins though.
> The FCC Output window provides details of the FCC process. 

Ahhhh, I see that is very useful, I just didn't know it was there!  The results window pops up.  Maybe a quick fix is to apply focus to the output window until results are ready?  Don't know if that is an easy thing to do....

**Comment by jadaml** [comment]
> @jadaml @jasells It appears that you have not noticed a critical aspect of FCC's behavior.
> 
> > RunInParallel					   By default tests run and then coverage is performed.  Set to true to run coverage immediately

My tests run faster if executed from command line non-parallel. Also, as they are currently are, I'm not certain they could run parallel at all. Neither of this I necessarily consider an issue with FCC

> Unless you have set RunInParallel Open Cover has not yet begun processing.

I may not quite understand how this works then. I'll look in to this when have the time for it.

> The FCC Window is for coverage results. It will clear when new coverage begins though.

On that note, could you perhaps change it so it only clears when the results are ready? I personally wouldn't mind reading the previous results while waiting for the next to come in. May be Gray it out as an indication of it being outdated?

> The FCC Output window provides details of the FCC process. It informs you of the following
> 
>     1. When it begins ( as controlled by your RunInParallel option )
> 
>     2. For each test project - that is running the cover tool and the arguments used
> 
>     3. Processing of the coverage report/s with ReportGenerator to generate the html report ( and a cobertura file used for the editor margin indicators )
> 
>     4. That we are further processing the output from ReportGenerator
> 
>     5. Success
>        Then we update the editor and the FCC Window

Yes, but when I was setting it up, didn't know about that. Also, it is hanging at the logo for me. I'll check if there is a verbosity setting for this, so I could properly troubleshoot this.

> So we always provide an indication that it is working and it only begins working when either the tests have all finished or you set RunInParallel. Perhaps what is missing then is a log message when RunInParallel is false - "You could speed up coverage by setting RunInParallel to true".

> We could provide a marque indicator that we are still processing but I cannot see how that provides any more information than we have started running the coverage tool and have not started the next step.

The idea is that when first trying to set it up, there would be a visual cue that it is working, and not idling around doing nothing at all as I first thought. This way, new comers don't get lost on how it works. And if that is not enough, you could look at the output window, true, but then you need to mention that in the documentation.

> We could write to the status bar but then we will be overwriting what the test explorer has written.

Don't do that then. 😉

P.s.: Sorry if my message is an inconsistent mess. It is late at night as I'm writing this on my phone and it may be a mess. I hope I was able to write a constructive response, and none comes off as rude. Also my current response didn't considered previous responses other than the immediate one, so it may be a step back. Sorry again, and will look in to it hopefully tomorrow.

**Comment by tonyhallett** [comment]
Hi everyone.
I have been working on the FCC Window showing log information in a similar manner to the FCC Output Window Pane ( less verbose ).  I am almost finished so will create a pull request tomorrow so you can try it out before it is released.

I will respond to these messages then too.

**Comment by tonyhallett** [comment]
https://github.com/FortuneN/FineCodeCoverage/pull/227

Please can you try below for a week and let me know if you encounter any issues.

Note that the Fine Code Coverage tool window is actually a WebBrowser control that works with NavigateToString and a lot of hacky code against the report that is generated for us.  There is C# javascript interop with InvokeScript and window.external for this new logging functionality and css styling with Visual Studio theme colours.  There is no nice front end framework / typescript available and as such there is a limitation to what can be achieved currently.

At some point there will be no need for the html generation step and React will be used against the coverage data.

I have not added parallel coverage for when there are multiple test projects ( via an option ) in this pr.

The docs have been updated to include the FCC output window pane - thanks for pointing that out !
The Fine Code Coverage Tool Window now has an additional tab, Coverage Log, that provides similar output to the output window pane.  You know when FCC is reacting to the test explorer as the tab will have an * in the name.  This * is removed when the coverage run is over ( completed, cancelled or exception ).
Only when completed will the other tabs change their information.

The time taken for the coverage to be completed by OpenCover or Coverlet is provided and this can be used to compare with running outside of FCC.


[[FineCodeCoverage ( zipped vsix)](https://github.com/FortuneN/FineCodeCoverage/suites/5256628398/artifacts/162102593)](https://github.com/FortuneN/FineCodeCoverage/suites/5256628398/artifacts/162102593)

[[FineCodeCoverage2022 ( zipped vsix)](https://github.com/FortuneN/FineCodeCoverage/suites/5256628398/artifacts/162102594)](https://github.com/FortuneN/FineCodeCoverage/suites/5256628398/artifacts/162102594)

**Comment by tonyhallett** [comment]
With additional link to Coverage Log tab of Fine Code Coverage window to show FCC Output Window Pane.

[vsix zipped 2019](https://github.com/FortuneN/FineCodeCoverage/suites/5278684325/artifacts/163347830)
[vsix zipped 2022](https://github.com/FortuneN/FineCodeCoverage/suites/5278684325/artifacts/163347831)

**Comment by tonyhallett** [comment]
Final update to this.

The font used in the Fine Code Coverage tool window ( WebBrowser control ) is taken from Tools / Options / Fonts and Colors /  Environment.

The font size is taken from Fonts and Colors and includes dpi scaling.  Before this commit there is a bug where dpi changes with visual studio open have no effect on the WebBrowser.  Hopefully this will fix https://github.com/FortuneN/FineCodeCoverage/issues/158.  I do not have multiple monitors so it would be appreciated if someone could follow the steps in the issue.

Whenever the environment font or dpi changes the webbrowser is updated via InvokeScript.  On my machine it appears to work well.

Please use the vsix below for the new functionality.

@FortuneN Unless informed otherwise I will release this in a week.

[vsix zipped 2019](https://github.com/FortuneN/FineCodeCoverage/suites/5279799680/artifacts/163408586)
[vsix zipped 2022](https://github.com/FortuneN/FineCodeCoverage/suites/5279799680/artifacts/163408587)

**Comment by tonyhallett** [comment]
@jadaml 

>  hanging at the logo for me. 

I don't know what you mean by that, can you elaborate ?
