### ISSUE TITLE
Add branch coverage data in FineCodeCoverage view's Coverage tab

### ISSUE THREAD

**Issue by guitax** [FortuneN/FineCodeCoverage#29]
### Description
Add branch coverage data to FineCodeCoverage view in "Coverage" tab.

### Current behavior
Only Line Coverage is shown in the "Coverage" tab.

### Expected behavior
Show also data for Branch Coverage like:
![image](https://user-images.githubusercontent.com/19864161/99706246-137a1f00-2a9b-11eb-82f3-ae81f835ac2f.png)

**Comment by FortuneN** [comment]
The concern i have is to have too eat up too much space so much so that we can't render class names properly.
Maybe i could render only 'the Branch coverage' chart and percentage but the the other columns ('Covered', 'Total')
![99706246-137a1f00-2a9b-11eb-82f3-ae81f835ac2f](https://user-images.githubusercontent.com/5636175/99719338-d884e500-2ab4-11eb-9f39-28068429c1ea.png)

What do you think?

**Comment by guitax** [comment]
Yeah, I understand your concern and I think your suggestion is ok.
Thank you, and good work by the way!

**Comment by tonyhallett** [comment]
@FortuneN 
It is necessary to show the branch coverage.
Consider the following report generated outside of Fine Code Coverage

![reporter_report](https://user-images.githubusercontent.com/11292998/103229280-a3c54280-492a-11eb-9fe1-8e847e8ba788.png)

If you were to look at the output window for Fine Code Coverage you would think that all was well with these tests.
![fccReport](https://user-images.githubusercontent.com/11292998/103229287-a758c980-492a-11eb-9402-1d4fc3f7fb49.png)

> The concern i have is to 'eat up' too much (horizontal) space so much so that we can't render class names properly or worse, horizontal scroll.

Class names go first so that is not a consideration. I don't think any user of the addin is going to consider horizontal scroll a problem if there is data there to be seen.

I personally think that the percentages are sufficient.  When the report view is provided by Fine Code Coverage itself ( https://github.com/FortuneN/FineCodeCoverage/issues/49 ) the other values could be provided as tool tips.

I would also include the additional functionality present in the webpage from the report generator - the grouping / filtering and facility to view the results for the individual methods ( that did not get 100% line coverage / branch coverage )

**Comment by t-johnson** [comment]
+1 for adding branch coverage.  if Horizontal space is an issue, then drop the colored bar that represents the percentages.  its duplicate information.
Perhaps could have it as an option to control what columns style is shown?

**Comment by FortuneN** [comment]
@t-johnson I think we need to keep the bar. I mostly just look at the bars and see how red there is and start working on that until i'm mostly green.

Anyways, the reason why this remains unresolved is that the easy way has a LOT of IO (+ time) cost. I need a bit of of time to handle it properly and i'm a bit short on time at the moment.

If you are interested in working on this we have have a discussion about the background so you can get started

**Comment by tonyhallett** [comment]
@FortuneN @t-johnson I am working on this.  Please do not do any work on this until I show my results as I have invested some time on it.

I will facilitate showing all all line and branch columns with options to exclude columns that you are not interested in.

**Comment by t-johnson** [comment]
@FortuneN 
Sure, I think the value of the visual bar might be good in some cases.  What might be better is to be able to view the summary down to the method/property level... but thats probably another problem all together.
@tonyhallett  let me know if you need help with testing.

**Comment by FortuneN** [comment]
@t-johnson
The current screen comes straight out of ReportGenerator (https://github.com/danielpalme/ReportGenerator) and for zero effort on my part; it has been a good start.

tonyhallett is working on the NEW AND IMPROVED :) custom screen.
Please discuss the ideas that you have and maybe we'll incorporate them into the new design.

**Comment by RichardPetheram** [comment]
How's progress on this? Branch coverage is a significant issue for me on current projects; if it will be available soon I would be amazingly happy. If not I'll need to look at setting up an interim solution on my projects - not trying to pressure, I just need to plan my work.

**Comment by tonyhallett** [comment]
@RichardPetheram 
I should be able to continue with the custom report in a week and certainly before 2 weeks time.

**Comment by AdelCaseware** [comment]
Any updates regarding this?

**Comment by tonyhallett** [comment]
On my radar.  It is the next FCC task.

**Comment by tonyhallett** [comment]
@RichardPetheram @AdelCaseware 

Latest version show branch coverage percentage column that can be sorted upon.
