### ISSUE TITLE
c# 8 switch expression always considered as not tested (red)

### ISSUE THREAD

**Issue by patattack78** [FortuneN/FineCodeCoverage#31]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Community 2019 Version 16.8.1
- This extension: 1.1.16
- Project Target Framework: .NET Core 3.1
- Unit Test Framework: NUnit, NUnit3TestAdapter

### Description
Replace this text with a short description

### Steps to recreate
Use [c# 8 switch expression](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/switch-expression).

1. Create an enum
2. Create the switch expression
```
    public enum InputType
    {
        Alpha,
        Numeric,
        AlphaNumeric,
    }

   public class MyClass
   {
        private InputType InputType { get; set; }

        private int SomeFunction()
        {
            return this.InputType switch
            {
                InputType.Alpha => 1,
                InputType.AlphaNumeric => 10,
                InputType.Numeric => 999,
                _ => throw new NotImplementedException(),
            };
        }
   }
```

### Current behaviour
When creating this type of code, the coverage report is not taking into consideration the c# 8 switch expression. It cannot tell what part of the switch was called. The reported lines are always in red whatever the code case was used.

### Expected behaviour
When creating this type of code, the coverage report should detect the c# 8 switch expression and evaluate the cases properly with green highlighting for the coverage report.

**Comment by FortuneN** [comment]
I believe this is related to this coverlet issue.
https://github.com/coverlet-coverage/coverlet/issues/936

I will have subscribed to get updates on that thread.
When that gets resolved, i will update the coverlet version on this extension.

I advise you go there and thumbs up the issue (as i have); They may be more motivated is they know that many of us are rooting for them to resolve the issue :)

**Comment by patattack78** [comment]
@FortuneN 
The fixed was merged a few hours ago :)
https://github.com/coverlet-coverage/coverlet/pull/1006

**Comment by tonyhallett** [comment]
@patattack78 This commit has not been released - FineCodeCoverage is using the most up to date version 1.7.2.

You can view the version from this link https://www.nuget.org/packages/coverlet.console

Whenever a new version of coverlet console is released this line will be updated 
https://github.com/FortuneN/FineCodeCoverage/blob/e434dc2d9cfe643a54c46e2dbda0849f25f4a5a2/FineCodeCoverage/Core/Coverlet/CoverletUtil.cs#L18
so that the latest version will be installed.

Perhaps it is possible to use the nightly build of https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/ConsumeNightlyBuild.md.  

Coverlet gets installed and runs from - C:\Users\tonyh\AppData\Local\FineCodeCoverage\coverlet
 
https://github.com/FortuneN/FineCodeCoverage/blob/e434dc2d9cfe643a54c46e2dbda0849f25f4a5a2/FineCodeCoverage/Core/Coverlet/CoverletUtil.cs#L99

I am not familiar with dotnet tool, perhaps @FortuneN knows if this is possible.

**Comment by FortuneN** [comment]
@tonyhallett Thank you for responding to this. I forgot to mention the part about the release.
@patattack78 @brendonparker Sorry

We have to wait for the coverlet release guys.
It IS possible to download the nightly build but eish ... IT'S THE NIGHTLY BUILD! Need i say more?

**Comment by tonyhallett** [comment]
@FortuneN true but given that releases are quarterly? and they are well behind the release schedule.

**Comment by patattack78** [comment]
It will get released at some point I was just pointing out that the fix had been merged on their end and well yes we need to wait on their release for the fix. It's progress :+1:

**Comment by mkhubbard** [comment]
Just a heads up that the coverlet packages that are supposed to include this fix have been released. Looks like a jump to v3.0.0.

**Comment by FortuneN** [comment]
@mkhubbard 👍  Will test and update soon. Thanks for heads up

**Comment by tonyhallett** [comment]
Version 3 has issues https://github.com/coverlet-coverage/coverlet/issues/1055

**Comment by tonyhallett** [comment]
@patattack78 
Latest [vsix](https://ci.appveyor.com/api/buildjobs/qyttaad09mdg3ral/artifacts/FineCodeCoverage.vsix) uses version 3.0.3 when going through the coverlet data collector.  Please [see](
https://github.com/FortuneN/FineCodeCoverage#coverlet-specific).

@FortuneN 
Good to update the global tool to match ?

**Comment by FortuneN** [comment]
Sounds good
