### ISSUE TITLE
Exclude in finecodecoverage-settings.xml not working

### ISSUE THREAD

**Issue by dingetje** [FortuneN/FineCodeCoverage#349]
### Installed product versions
- Visual Studio: [example 2022 Professional]
- This extension: [example 1.1.194]

### Description
Exclude in finecodecoverage-settings.xml not working as expected

### Steps to recreate
1. Install Fine Code Coverage Add-on
2. Add finecodecoverage-settings.xml to project
3. Add Exclude pattern in finecodecoverage-settings.xml based on namespace
4. Run unit tests
5. Code coverage report still shows excluded namespace classes

### Current behavior
Exclude settings seem to be ignored

### Expected behavior
Exclude pattern should be applied to code coverage setting

### Side Notes
- the only settings that seem to work are the ModulePathExclude

**Comment by dingetje** [comment]
Here's my anonymized finecodecoverage-settings.xml 
````
<FineCodeCoverage>
	<Enabled>
		True
	</Enabled>
	<Exclude>
		[*]FooNameSpace.*
	</Exclude>
	<ExcludeByFile>
		**/XSDGenerated.designer.cs
	</ExcludeByFile>
	<ExcludeByAttribute>
	</ExcludeByAttribute>
	<ModulePathsExclude>
		.*UnitTests.dll
		.*Moq.dll
	</ModulePathsExclude>
</FineCodeCoverage>
````

**Comment by tonyhallett** [comment]
The expected behaviour is that the applicable settings for the coverage provider in use should be applied, and they are.  You can see that in the FCC output pane of the Visual Studio output window.

You have a mixture of coverage settings.  ModulePathsExclude is an ms code coverage settings whereas Exclude / ExcludeByFile and ExcludeByAttribute are OpenCover / Coverlet settings ( non ms code coverage ).
