### ISSUE TITLE
Command that can be executed in the a BuildServer (gitHub for example)

### ISSUE THREAD

**Issue by aboimpinto** [FortuneN/FineCodeCoverage#356]
### Installed product versions
- Visual Studio: VS2022
- This extension: 1.1.195

### Description
What command should I run in the build server to create the report?
I already have a finecodecoverage-settings.xml in the same folder as the solution.

### Current behavior
Can only get the report when I run from VS2022

### Expected behavior
Be able to create the full report in the build server and for that build the TestCoverage Report

**Comment by tonyhallett** [comment]
I have already stated that FCC does not run on a build server ( admittedly not as clear as I would have liked due to the mark up )
https://github.com/FortuneN/FineCodeCoverage/issues/354#issuecomment-1748899311 

<img width="369" alt="image" src="https://github.com/FortuneN/FineCodeCoverage/assets/11292998/c93b08de-a851-4a87-9c3f-808fdcf648b3">

FCC hooks into the test explorer and is capable of generating run settings for you.  FCC uses ReportGenerator to create the html report you see in our tool window.

Your alternative is outlined here https://learn.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022#specify-a-run-settings-file-from-the-command-line
and here https://github.com/danielpalme/ReportGenerator/wiki/Integration#github-actions

Be sure to use ResultsDirectory so you can find the cobertura file for ReportGenerator "reports".
Note that FCC uses an earlier version or ReportGenerator and customize the results - but I expect that this should not be an issue.

**Comment by aboimpinto** [comment]
thanks ... I hope one day you will be able to implement this feature
