### ISSUE TITLE
Code coverage fails if deterministic build is enabled for project

### ISSUE THREAD

**Issue by dozer75** [FortuneN/FineCodeCoverage#4]
### Installed product versions
- Visual Studio: 2019 Community 16.7.2
- This extension: 1.0.39

### Description
The code coverage does not work when deterministic build are configured for the projects that is being tested.

This issue is caused by the problem I mentioned [here](https://github.com/coverlet-coverage/coverlet/issues/942) and a suggestion to how to fix this when I run Coverlet in my code was suggested and worked. However it seems that this extension doesn't handle it.

### Steps to recreate
1. Have a project that has deterministic build enabled
2. Run tests on that project

### Current behavior
No coverage is displayed and the Finde code coverage log shows message similar to the problem mentioned in description.

### Expected behavior
The code coverage routine should work with deterministic builds. Refer to the link above.

**Comment by dozer75** [comment]
Can't see if this is fixed or not, but it still doesn't work so I'll guess it not adressed yet.

**Comment by FortuneN** [comment]
**What we know : Sources**
1. https://github.com/coverlet-coverage/coverlet/issues/942 [dozer75 & Coverlet team]
2. https://github.com/clairernovotny/DeterministicBuilds.git [.NET team]
3. https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/DeterministicBuild.md [Coverlet team]
4. This extension uses Coverlet to analyze build output [Fine Code Coverage team]

**What we know : Summarized**
- Deterministic builds require a property to be set to true during **CI**: ContinuousIntegrationBuild.
These should **not** be enabled during local dev or the debugger _(or Coverlet; therefore Fine Code Coverage)_ won't be able to find the local source files.
Therefore, you should use your CI system's variable to set them conditionally
(CI examples and a workaround given)
[Source 2]
- From coverage perspective deterministic build put some challenge because usually coverage **tools need access to source file metadata (ie. local path) during instrumentation and report generation**.
These files are reported inside pdb files, where are stored debugging information needed by debuggers and also by tools that needs to work with "build" metadata information, for example generated dll modules and source files used.
**In local (non-CI) builds metadata emitted to pdbs are not "deterministic", that means that for instance source files path are reported with full path.**
Finally ... (with the ContinuousIntegrationBuild property set to true) ... we can validate artifacts and be sure that binary was built from a specific sources (**because there is no hard-coded variables metadata like paths from different build machines**).
(workaround given)
[Source 3]

**Some thoughts given what we know**
- It seems the recommended way is to make sure that **ContinuousIntegrationBuild** is disabled during local development where debuggers and other tools like Coverlet _(therefore Fine Code Coverage)_ need to be able to inspect none-deterministic build output which contains all the required metadata.
[Source 2 shows how to enable ContinuousIntegrationBuild conditionally in CI systems; Azure DevOps and GitHub actions for example]
- Source 2 and 3 both provide a workarounds IF you should wish to keep ContinuousIntegrationBuild enabled during local development

**Conclusion**
Fine Code Coverage comes into play after the build is already done so there is not much we can do in this extension.
The least we can do is publish these findings for the benefit of other users we may encounter this issue.
I will create a Known Issues list and reference this issue (our first know issue)
I will await community (@dozer75, you're it) feedback on this and close this issue after some time

**Comment by dozer75** [comment]
Well, if it's not possible to solve there are workarounds for this issue :)

**Comment by FortuneN** [comment]
Please post a review https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage&ssr=false#review-details

and/or

Star this repo
