### ISSUE TITLE
Report links do not work when package has _ in name

### ISSUE THREAD

**Issue by tonyhallett** [FortuneN/FineCodeCoverage#43]
### Installed product versions
- Visual Studio: [Community 16.8.3]
- This extension: [example 1.1.39]

### Description
Given a Test project that tests XUnit_Conditional_Fact with class ConditionalFact
When click ConditionalFact in the OutputToolWindowControl the ScriptManager.OpenFile will be called.
`

		public void OpenFile(string htmlFilePath, int file, int line)
		{
			// Note : There may be more than one file; e.g. in the case of partial classes

			var htmlFileName = Path.GetFileNameWithoutExtension(htmlFilePath);
			var sourceFiles = FCCEngine.GetSourceFilesFromReportGeneratorHtmlFileName(htmlFileName);
`
This is the htmlFilePath argument.
"C:\\Users\\tonyh\\Source\\Repos\\XUnit_Conditional_Fact\\Test\\bin\\Debug\\net472\\fine-code-coverage\\_outputfolder\\XUnit_Conditional_Fact_ConditionalFact.html"

htmlFileName becomes "XUnit_Conditional_Fact_ConditionalFact"

The problem arises in the FCCEngine.GetSourceFilesFromReportGeneratorHtmlFileName

`
public static string[] GetSourceFilesFromReportGeneratorHtmlFileName(string htmlFileNameWithoutExtension)
		{
			// Note : There may be more than one file; e.g. in the case of partial classes

			var html_file_tokens = htmlFileNameWithoutExtension.Split(new[] { '_' }, 2);
			var html_file_package = html_file_tokens.First();
			var html_file_class = $".{html_file_tokens.Last()}";
`
The code above gives the html_file_package as XUnit, html_file_class as ".Conditional_Fact_ConditionalFact" which is obviously incorrect.

Without knowing the Cobertura format and the transformation to html by the report generator I cannot provide a surefire correction to your code.  In this particular instance this change would work

`

            var underscoreSeparatorIndex = htmlFileNameWithoutExtension.LastIndexOf('_');
            var html_file_package = htmlFileNameWithoutExtension.Substring(0,underscoreSeparatorIndex);
            var html_file_class = $".{htmlFileNameWithoutExtension.Substring(underscoreSeparatorIndex+1)}";
`

**Comment by FortuneN** [comment]
Firstly, thank you for a well-reasoned analysis (for this issue and the others that you have posted; THANK YOU).

The problem arises from the fact that I'm trying to get a \<package\>.\<namespace\>.\<class\> from a presentation file (html).
Normally, when you click on a class name, it just navigates to the relevant coverage detail html file for that class.

The author of the ReportGenerator tool did not have a reason to consider that someone (me) would be crazy enough to hijack that event in order to identity and open a source file in an IDE, so there isn't sufficient metadata to do that without some gymnastics.

The solution you've proposed runs into the same issue if the namespace or class name also has a least one underscore.

There is some hope though.

At rest (before some javascript runs) a hyperlink looks like this:

`<a href="AA_BB.Library_InvoiceDto.html">AA_BB.Library.DTOs.InvoiceDto</a>` 

while in the browser (after javascript runs) the same hyperlink looks like this:

`<a href="#AA_BB.Library_InvoiceDto.html">InvoiceDto</a>`

The first one has all the data we need and if, while pre-processing the html output, we embedded the full name as an attribute on that hyperlink it should hopefully produce (in the browser) something like:

`<a href="#AA_BB.Library_InvoiceDto.html" fullname="AA_BB.Library.DTOs.InvoiceDto">InvoiceDto</a>`

which we can resolve more easily.

In this method, you will see that i do some messing around the with html file (to add tabs, remove some columns, e.t.c)

https://github.com/FortuneN/FineCodeCoverage/blob/b803afaafc007df6b69534630b7e5ca280e7d78a/FineCodeCoverage/Core/ReportGenerator/ReportGeneratorUtil.cs#L239

We can do the embedding here and then in the following section:

https://github.com/FortuneN/FineCodeCoverage/blob/b803afaafc007df6b69534630b7e5ca280e7d78a/FineCodeCoverage/Core/ReportGenerator/ReportGeneratorUtil.cs#L336-L345

we can modify the javascript to read the custom attribute (fullname) and pass that along instead of the 'href' on click.

What do think about this approach?
Since you have started on this, let me know if you would like to take another stab at it (or should i?)

**Comment by tonyhallett** [comment]
> The solution you've proposed runs into the same issue if the namespace or class name also has a least one underscore.

Yes quite correct ! Sorry was needing a quick solution to my issue.

I will use your idea and create a pull request tomorrow.
