### ISSUE TITLE
Coverage sometimes stops being displayed in VS editor window

### ISSUE THREAD

**Issue by bjornhellander** [FortuneN/FineCodeCoverage#455]
### Installed product versions
- Visual Studio: 2022 Community, 17.11.3
- This extension: 1.1.223

### Description
First off: Awesome extension!

I have however had trouble with coverage not being displayed lately (the coloring in the "vertical bars" in the editor windows).
So far, a `git clean -fdx` has made it work again, but the problem keeps coming back again after a while.
I have only noticed it the last week or so, but it might have happened earlier as well.

### Steps to recreate
I have not been able to see a pattern yet. I just keep developing and running tests and after a while no coverage is displayed.

### Current behavior
Coverage sometimes stops being displayed.

### Expected behavior
Coverage should always be displayed after running tests.

### Side Notes
 - Right now it is working in all repositories that I have tested, but just let me know if you would like me to check anything when it's not working.

**Comment by bjornhellander** [comment]
Options:

![image](https://github.com/user-attachments/assets/f21f5547-b070-4a78-a975-cc400d3aada3)

![image](https://github.com/user-attachments/assets/bc4af282-7efd-4204-abad-5680d7425dc5)

**Comment by tonyhallett** [comment]
Are you changing files outside of the Vs editor ?

**Comment by tonyhallett** [comment]
You have also the dirty code indicators turned off. If you edit code since the last coverage it becomes dirty.

**Comment by bjornhellander** [comment]
> Are you changing files outside of the Vs editor ?

Solution and project files occasionally, but not source files as far as I can recall.

**Comment by tonyhallett** [comment]
Git checkouts ?

**Comment by bjornhellander** [comment]
> Git checkouts ?

You mean if I do that outside of VS? No.

**Comment by tonyhallett** [comment]
When indicators are being shown the files are being tracked so that adding new code between the tested code results in the coverage indictors moving up and down.  When you close a file we save the coverage indicator information for when you reopen the file ( if you rename the file we update this store with the new name ).

When a file is opened and there has been coverage collected the store is checked.  If the information is in the store but the last write time of the file is after the save time then our data is out of date and of no use and you should see a message in the FCC Output Window Pane with "Not creating editor marks for {this.textInfo.FilePath} as coverage is out of date".  If we have not stored coverage info for the file and the file last write time is after the last test execution started then the previously collected coverage is again out of date.
After a file is opened and a new coverage result is collected it will be considered out of date if the file last write time is after the time of the test that initiated the coverage.  Again there will be a message in the FCC Output window.
	
So if you get unexpected file indicators then check the FCC output and turn on all indicators if you do not see a log entry in case your expected covered/uncovered/partially covered has become dirty or is being considered new.

**Comment by tonyhallett** [comment]
The tracking of the code lines is performed using ITrackingSpan and ITextSnapshot.  It is possible that the logic is not working correctly when files are open when a checkout occurs.  If this is indeed the cause of the issue then you should collect coverage again.

**Comment by bjornhellander** [comment]
This came back so fast before, so I thought it would again, but hasn't happened yet. I close this now and will return if I see it again.
