### ISSUE TITLE
Sorting by covered/total branches doesn't work across assemblies

### ISSUE THREAD

**Issue by ekolis** [FortuneN/FineCodeCoverage#474]
### Installed product versions
- Visual Studio: 2022 Professional
- This extension: 1.1.229

### Description
When attempting to sort the coverage data by covered branches or total branches, nothing happens to the assemblies; they are not sorted by their covered/total branches (as with other sort columns, like total lines of code or branch coverage) and only the individual entries inside the assemblies are sorted.

### Steps to recreate
1. Open code coverage
2. Run tests
3. Set detail level to assembly
4. Collapse all
5. Try to sort by covered branches or total branches by clicking one of those headers.

### Current behavior
The assemblies are not sorted.

### Expected behavior
The assemblies should be sorted by the chosen criteria.

**Comment by tonyhallett** [comment]
The Branch coverage column sorts in this manner - though it is percentages rather than Covered / Total.
Again there will be no devlopment on the report that Report Generator provides.  Although we do not use the current version due to issues with WebBrowser control the current version of ReportGenerator sorts in the same manner.
